from __future__ import annotations

# Candidate generation heuristics
CANDIDATE_MIN_KEYWORD_LENGTH = 4
CANDIDATE_SHARED_KEYWORD_CAP = 5
CANDIDATE_SHARED_KEYWORD_WEIGHT = 4
CANDIDATE_SHARED_ENTITY_CAP = 3
CANDIDATE_SHARED_ENTITY_WEIGHT = 6
CANDIDATE_SAME_CATEGORY_BONUS = 6
CANDIDATE_SAME_DATE_BUCKET_BONUS = 6
CANDIDATE_TITLE_SIMILARITY_THRESHOLD = 0.5
CANDIDATE_TITLE_SIMILARITY_WEIGHT = 30
CANDIDATE_PAIR_SCORE_THRESHOLD = 18
CANDIDATE_MAX_PAIRS_PER_MARKET = 20
CANDIDATE_KEYWORD_INDEX_MAX_BUCKET_SIZE = 40
CANDIDATE_ENTITY_INDEX_MAX_BUCKET_SIZE = 25
CANDIDATE_DATE_BUCKET_INDEX_MAX_BUCKET_SIZE = 20

# Relation analysis heuristics
RULE_ONLY_CONFIDENCE_THRESHOLD = 0.9
EXCLUSIVE_WIN_EVENT_SIMILARITY_THRESHOLD = 0.78
EXCLUSIVE_WIN_RELATION_STRENGTH = 0.92
EXCLUSIVE_WIN_CONFIDENCE = 0.9
DEADLINE_SUBSET_CORE_SIMILARITY_THRESHOLD = 0.78
DEADLINE_SUBSET_RELATION_STRENGTH = 0.88
DEADLINE_SUBSET_CONFIDENCE = 0.84
THRESHOLD_SUBSET_CORE_SIMILARITY_THRESHOLD = 0.8
THRESHOLD_SUBSET_RELATION_STRENGTH = 0.86
THRESHOLD_SUBSET_CONFIDENCE = 0.82
NEAR_DUPLICATE_OVERLAP_SIMILARITY_THRESHOLD = 0.88
NEAR_DUPLICATE_OVERLAP_RELATION_STRENGTH = 0.7
NEAR_DUPLICATE_OVERLAP_CONFIDENCE = 0.62
RELATION_RESULT_CONFLICT_CONFIDENCE_DELTA_THRESHOLD = 0.1
RELATION_RESULT_AMBIGUOUS_CONFIDENCE_PENALTY = 0.1
FALLBACK_RELATION_STRENGTH = 0.1
FALLBACK_CONFIDENCE = 0.15
LLM_LOGICAL_RELATION_MIN_SHARED_TITLE_KEYWORDS = 2
LLM_LOGICAL_RELATION_TITLE_SIMILARITY_THRESHOLD = 0.35

# Opportunity scoring heuristics
EXCLUSIVE_MIN_EXCESS_THRESHOLD = 0.02
EXCLUSIVE_HARD_ARB_EXCESS_THRESHOLD = 0.06
EXCLUSIVE_HARD_ARB_CONFIDENCE_THRESHOLD = 0.82
EXCLUSIVE_HARD_ARB_RELATION_STRENGTH_THRESHOLD = 0.8
EXCLUSIVE_SCORE_EXCESS_WEIGHT = 340
EXCLUSIVE_SCORE_CONFIDENCE_WEIGHT = 18
EXCLUSIVE_SCORE_RELATION_STRENGTH_WEIGHT = 16

IMPLICATION_MIN_GAP_THRESHOLD = 0.02
IMPLICATION_HARD_ARB_GAP_THRESHOLD = 0.07
IMPLICATION_HARD_ARB_CONFIDENCE_THRESHOLD = 0.85
IMPLICATION_HARD_ARB_RELATION_STRENGTH_THRESHOLD = 0.82
IMPLICATION_SCORE_GAP_WEIGHT = 380
IMPLICATION_SCORE_CONFIDENCE_WEIGHT = 15
IMPLICATION_SCORE_RELATION_STRENGTH_WEIGHT = 15

NEGATIVE_CORRELATION_MIN_JOINT_RICHNESS_THRESHOLD = 0.08
NEGATIVE_CORRELATION_SCORE_JOINT_RICHNESS_WEIGHT = 220
NEGATIVE_CORRELATION_SCORE_CONFIDENCE_WEIGHT = 12
NEGATIVE_CORRELATION_SCORE_RELATION_STRENGTH_WEIGHT = 12

POSITIVE_CORRELATION_MIN_DIVERGENCE_THRESHOLD = 0.18
POSITIVE_CORRELATION_SCORE_DIVERGENCE_WEIGHT = 180
POSITIVE_CORRELATION_SCORE_CONFIDENCE_WEIGHT = 10
POSITIVE_CORRELATION_SCORE_RELATION_STRENGTH_WEIGHT = 10
